import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import CardWrapper from "../components/categories/cardWrapper";
import RouteToLogin from "../components/categories/routeToLogin";

const Home: NextPage = () => {
  const [token, setToken] = useState("");
  const [isLogin, setIsLogin] = useState(false);

  useEffect(() => {
    function assign() {
      if (typeof window !== undefined) {
        setToken(sessionStorage.getItem("token"));
        if (token !== undefined || token !== "") {
          setIsLogin(true);
        }
      }
    }
    assign();
  }, [token]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Nine Dragon Labs Blog</h1>
        {isLogin ? <CardWrapper /> : <RouteToLogin />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
